/// Emits an Android VectorDrawable (`<vector>`) from an [SvgDocument].
///
/// This is the heart of the "vector-native" value prop: no rasterisation, paths
/// pass through verbatim, and the result is crisp at every density. Used for the
/// adaptive icon foreground / background / monochrome layers.
library;

import 'package:xml/xml.dart';

import '../geometry/adaptive_geometry.dart';
import '../graphic/svg_document.dart';

class VectorDrawableWriter {
  VectorDrawableWriter({this.warnings});

  /// Optional sink for non-fatal conversion notes (shear dropped, etc.).
  final List<String>? warnings;

  static const _ns = 'http://schemas.android.com/apk/res/android';

  /// Builds a VectorDrawable.
  ///
  /// - [viewport] sets `viewportWidth/Height`. For adaptive layers this is the
  ///   108 canvas; the source art is mapped into it via [fit].
  /// - [fit] (optional) wraps all content in a scale+translate group so the art
  ///   lands inside the safe zone.
  /// - [sizeDp] sets `android:width/height`.
  /// - [viewportHeight] / [sizeDpHeight] override the height for non-square art
  ///   (e.g. a wide branding wordmark); they default to the square values.
  String build(
    SvgDocument doc, {
    required double viewport,
    AdaptiveFit? fit,
    double sizeDp = 108,
    double? viewportHeight,
    double? sizeDpHeight,
  }) {
    final vpH = viewportHeight ?? viewport;
    final szH = sizeDpHeight ?? sizeDp;
    final builder = XmlBuilder();
    builder.processing('xml', 'version="1.0" encoding="utf-8"');
    builder.comment(' Generated by flutter_adaptive_studio. Do not edit. ');
    builder.element('vector', namespaceUris: {'android': _ns}, nest: () {
      builder.attribute('width', '${_fmt(sizeDp)}dp', namespaceUri: _ns);
      builder.attribute('height', '${_fmt(szH)}dp', namespaceUri: _ns);
      builder.attribute('viewportWidth', _fmt(viewport), namespaceUri: _ns);
      builder.attribute('viewportHeight', _fmt(vpH), namespaceUri: _ns);

      if (fit != null && !fit.isIdentity) {
        builder.element('group', nest: () {
          builder.attribute('scaleX', _fmt(fit.scale), namespaceUri: _ns);
          builder.attribute('scaleY', _fmt(fit.scale), namespaceUri: _ns);
          builder.attribute('translateX', _fmt(fit.translateX),
              namespaceUri: _ns);
          builder.attribute('translateY', _fmt(fit.translateY),
              namespaceUri: _ns);
          _emitNodes(builder, doc.children);
        });
      } else {
        _emitNodes(builder, doc.children);
      }
    });

    return builder.buildDocument().toXmlString(pretty: true, indent: '    ');
  }

  void _emitNodes(XmlBuilder b, List<SvgNode> nodes) {
    for (final node in nodes) {
      switch (node) {
        case SvgGroup g:
          _emitGroup(b, g);
        case SvgPath p:
          _emitPath(b, p);
      }
    }
  }

  void _emitGroup(XmlBuilder b, SvgGroup g) {
    if (g.transform.isIdentity) {
      _emitNodes(b, g.children);
      return;
    }
    final t = g.transform.decompose();
    if (t.shear.abs() > 1e-3) {
      warnings?.add(
          'Skew/shear in transform "${g.rawTransform}" is not representable '
          'in a VectorDrawable group and was approximated.');
    }
    b.element('group', nest: () {
      if (t.translateX != 0) {
        b.attribute('translateX', _fmt(t.translateX), namespaceUri: _ns);
      }
      if (t.translateY != 0) {
        b.attribute('translateY', _fmt(t.translateY), namespaceUri: _ns);
      }
      if (t.rotation != 0) {
        b.attribute('rotation', _fmt(t.rotation), namespaceUri: _ns);
      }
      if (t.scaleX != 1) {
        b.attribute('scaleX', _fmt(t.scaleX), namespaceUri: _ns);
      }
      if (t.scaleY != 1) {
        b.attribute('scaleY', _fmt(t.scaleY), namespaceUri: _ns);
      }
      _emitNodes(b, g.children);
    });
  }

  void _emitPath(XmlBuilder b, SvgPath p) {
    b.element('path', nest: () {
      if (p.name != null && p.name!.isNotEmpty) {
        b.attribute('name', p.name!, namespaceUri: _ns);
      }
      b.attribute('pathData', _normalizePathData(p.pathData),
          namespaceUri: _ns);
      if (!p.fill.isNone) {
        b.attribute('fillColor', p.fill.androidHex, namespaceUri: _ns);
        if (p.fillAlpha < 0.999) {
          b.attribute('fillAlpha', _fmt(p.fillAlpha), namespaceUri: _ns);
        }
      }
      if (!p.stroke.isNone && p.strokeWidth > 0) {
        b.attribute('strokeColor', p.stroke.androidHex, namespaceUri: _ns);
        b.attribute('strokeWidth', _fmt(p.strokeWidth), namespaceUri: _ns);
        if (p.strokeAlpha < 0.999) {
          b.attribute('strokeAlpha', _fmt(p.strokeAlpha), namespaceUri: _ns);
        }
      }
    });
  }

  /// Collapses whitespace in path data so the attribute stays single-line.
  static String _normalizePathData(String d) =>
      d.replaceAll(RegExp(r'\s+'), ' ').trim();

  static String _fmt(double v) {
    if (v == v.roundToDouble()) return v.toInt().toString();
    return v
        .toStringAsFixed(4)
        .replaceAll(RegExp(r'0+$'), '')
        .replaceAll(RegExp(r'\.$'), '');
  }
}
