/// Emits an Android VectorDrawable (`<vector>`) from an [SvgDocument].
///
/// This is the heart of the "vector-native" value prop: no rasterisation, paths
/// pass through verbatim, and the result is crisp at every density. Used for the
/// adaptive icon foreground / background / monochrome layers.
library;

import 'dart:math' as math;

import 'package:xml/xml.dart';

import '../geometry/adaptive_geometry.dart';
import '../graphic/path_data.dart';
import '../graphic/svg_document.dart';

class VectorDrawableWriter {
  VectorDrawableWriter({this.warnings});

  /// Optional sink for non-fatal conversion notes (shear dropped, etc.).
  final List<String>? warnings;

  static const _ns = 'http://schemas.android.com/apk/res/android';
  static const _aaptNs = 'http://schemas.android.com/aapt';

  /// Builds a VectorDrawable.
  ///
  /// - [viewport] sets `viewportWidth/Height`. For adaptive layers this is the
  ///   108 canvas; the source art is mapped into it via [fit].
  /// - [fit] (optional) wraps all content in a scale+translate group so the art
  ///   lands inside the safe zone.
  /// - [sizeDp] sets `android:width/height`.
  /// - [viewportHeight] / [sizeDpHeight] override the height for non-square art
  ///   (e.g. a wide branding wordmark); they default to the square values.
  String build(
    SvgDocument doc, {
    required double viewport,
    AdaptiveFit? fit,
    double sizeDp = 108,
    double? viewportHeight,
    double? sizeDpHeight,
  }) {
    final vpH = viewportHeight ?? viewport;
    final szH = sizeDpHeight ?? sizeDp;
    final builder = XmlBuilder();
    builder.processing('xml', 'version="1.0" encoding="utf-8"');
    builder.comment(' Generated by flutter_adaptive_studio. Do not edit. ');
    // `aapt:attr` (for inline gradients) is only declared when the art uses one.
    final nsUris = _hasGradient(doc.children)
        ? {'android': _ns, 'aapt': _aaptNs}
        : {'android': _ns};
    builder.element('vector', namespaceUris: nsUris, nest: () {
      builder.attribute('width', '${_fmt(sizeDp)}dp', namespaceUri: _ns);
      builder.attribute('height', '${_fmt(szH)}dp', namespaceUri: _ns);
      builder.attribute('viewportWidth', _fmt(viewport), namespaceUri: _ns);
      builder.attribute('viewportHeight', _fmt(vpH), namespaceUri: _ns);

      if (fit != null && !fit.isIdentity) {
        builder.element('group', nest: () {
          builder.attribute('scaleX', _fmt(fit.scale), namespaceUri: _ns);
          builder.attribute('scaleY', _fmt(fit.scale), namespaceUri: _ns);
          builder.attribute('translateX', _fmt(fit.translateX),
              namespaceUri: _ns);
          builder.attribute('translateY', _fmt(fit.translateY),
              namespaceUri: _ns);
          _emitNodes(builder, doc.children);
        });
      } else {
        _emitNodes(builder, doc.children);
      }
    });

    return builder.buildDocument().toXmlString(pretty: true, indent: '    ');
  }

  /// True if any node in the tree fills with a gradient (so `aapt:attr` must be
  /// declared on the root vector).
  static bool _hasGradient(List<SvgNode> nodes) {
    for (final n in nodes) {
      switch (n) {
        case SvgGroup g:
          if (_hasGradient(g.children)) return true;
        case SvgPath p:
          if (p.fillGradient != null) return true;
      }
    }
    return false;
  }

  void _emitNodes(XmlBuilder b, List<SvgNode> nodes) {
    for (final node in nodes) {
      switch (node) {
        case SvgGroup g:
          _emitGroup(b, g);
        case SvgPath p:
          _emitPath(b, p);
      }
    }
  }

  void _emitGroup(XmlBuilder b, SvgGroup g) {
    final identity = g.transform.isIdentity;
    // A plain identity group with no clip flattens into its parent.
    if (identity && g.clipPathData == null) {
      _emitNodes(b, g.children);
      return;
    }
    b.element('group', nest: () {
      if (!identity) {
        final t = g.transform.decompose();
        if (t.shear.abs() > 1e-3) {
          warnings?.add(
              'Skew/shear in transform "${g.rawTransform}" is not representable '
              'in a VectorDrawable group and was approximated.');
        }
        if (t.translateX != 0) {
          b.attribute('translateX', _fmt(t.translateX), namespaceUri: _ns);
        }
        if (t.translateY != 0) {
          b.attribute('translateY', _fmt(t.translateY), namespaceUri: _ns);
        }
        if (t.rotation != 0) {
          b.attribute('rotation', _fmt(t.rotation), namespaceUri: _ns);
        }
        if (t.scaleX != 1) {
          b.attribute('scaleX', _fmt(t.scaleX), namespaceUri: _ns);
        }
        if (t.scaleY != 1) {
          b.attribute('scaleY', _fmt(t.scaleY), namespaceUri: _ns);
        }
      }
      if (g.clipPathData != null) _emitClipPath(b, g.clipPathData!);
      _emitNodes(b, g.children);
    });
  }

  void _emitClipPath(XmlBuilder b, String pathData) {
    b.element('clip-path', nest: () {
      b.attribute('pathData', _normalizePathData(pathData), namespaceUri: _ns);
    });
  }

  void _emitPath(XmlBuilder b, SvgPath p) {
    // A clip on a bare path is expressed by wrapping it in a group
    // (VectorDrawable clip-paths live on groups, not paths).
    if (p.clipPathData != null) {
      b.element('group', nest: () {
        _emitClipPath(b, p.clipPathData!);
        _emitPathBody(b, p);
      });
      return;
    }
    _emitPathBody(b, p);
  }

  void _emitPathBody(XmlBuilder b, SvgPath p) {
    b.element('path', nest: () {
      if (p.name != null && p.name!.isNotEmpty) {
        b.attribute('name', p.name!, namespaceUri: _ns);
      }
      b.attribute('pathData', _normalizePathData(p.pathData),
          namespaceUri: _ns);
      if (p.fillGradient != null) {
        if (p.fillAlpha < 0.999) {
          b.attribute('fillAlpha', _fmt(p.fillAlpha), namespaceUri: _ns);
        }
        _emitGradientFill(b, p.fillGradient!, p);
      } else if (!p.fill.isNone) {
        b.attribute('fillColor', p.fill.androidHex, namespaceUri: _ns);
        if (p.fillAlpha < 0.999) {
          b.attribute('fillAlpha', _fmt(p.fillAlpha), namespaceUri: _ns);
        }
      }
      if (!p.stroke.isNone && p.strokeWidth > 0) {
        b.attribute('strokeColor', p.stroke.androidHex, namespaceUri: _ns);
        b.attribute('strokeWidth', _fmt(p.strokeWidth), namespaceUri: _ns);
        if (p.strokeAlpha < 0.999) {
          b.attribute('strokeAlpha', _fmt(p.strokeAlpha), namespaceUri: _ns);
        }
      }
    });
  }

  /// Emits `<aapt:attr name="android:fillColor"><gradient .../></aapt:attr>`.
  /// Coordinates resolve to user space (objectBoundingBox mapped through the
  /// path bounds) with the `gradientTransform` baked into the endpoints/centre.
  void _emitGradientFill(XmlBuilder b, SvgGradient g, SvgPath path) {
    final geo = _gradientGeometry(g, path);
    b.element('attr', namespaceUri: _aaptNs, nest: () {
      b.attribute('name', 'android:fillColor');
      b.element('gradient', nest: () {
        b.attribute('type', g.linear ? 'linear' : 'radial', namespaceUri: _ns);
        if (g.linear) {
          b.attribute('startX', _fmt(geo.x1), namespaceUri: _ns);
          b.attribute('startY', _fmt(geo.y1), namespaceUri: _ns);
          b.attribute('endX', _fmt(geo.x2), namespaceUri: _ns);
          b.attribute('endY', _fmt(geo.y2), namespaceUri: _ns);
        } else {
          b.attribute('centerX', _fmt(geo.cx), namespaceUri: _ns);
          b.attribute('centerY', _fmt(geo.cy), namespaceUri: _ns);
          b.attribute('gradientRadius', _fmt(geo.r), namespaceUri: _ns);
        }
        b.attribute('tileMode', g.tileMode, namespaceUri: _ns);
        for (final s in g.stops) {
          b.element('item', nest: () {
            b.attribute('offset', _fmt(s.offset), namespaceUri: _ns);
            b.attribute('color', s.color.androidHex, namespaceUri: _ns);
          });
        }
      });
    });
  }

  /// Resolves a gradient's coordinates to user space, baking the
  /// `gradientTransform` into the endpoints (linear) or centre + radius (radial).
  ({double x1, double y1, double x2, double y2, double cx, double cy, double r})
      _gradientGeometry(SvgGradient g, SvgPath path) {
    final bb = g.userSpace
        ? null
        : (path.explicitBounds ?? PathData.bounds(path.pathData));
    final minX = bb?.minX ?? 0.0, minY = bb?.minY ?? 0.0;
    final w = bb?.width ?? 1.0, h = bb?.height ?? 1.0;
    double mx(double v) => g.userSpace ? v : minX + v * w;
    double my(double v) => g.userSpace ? v : minY + v * h;
    if (g.linear) {
      final p1 = g.transform.apply(mx(g.x1), my(g.y1));
      final p2 = g.transform.apply(mx(g.x2), my(g.y2));
      return (x1: p1.x, y1: p1.y, x2: p2.x, y2: p2.y, cx: 0, cy: 0, r: 0);
    }
    final c = g.transform.apply(mx(g.cx), my(g.cy));
    final tr = g.transform;
    final scale = math.sqrt((tr.a * tr.d - tr.b * tr.c).abs());
    final baseR = g.userSpace ? g.r : g.r * (w + h) / 2;
    return (x1: 0, y1: 0, x2: 0, y2: 0, cx: c.x, cy: c.y, r: baseR * scale);
  }

  /// Collapses whitespace in path data so the attribute stays single-line.
  static String _normalizePathData(String d) =>
      d.replaceAll(RegExp(r'\s+'), ' ').trim();

  static String _fmt(double v) {
    if (v == v.roundToDouble()) return v.toInt().toString();
    return v
        .toStringAsFixed(4)
        .replaceAll(RegExp(r'0+$'), '')
        .replaceAll(RegExp(r'\.$'), '');
  }
}
