/// Templates emitted for the splash feature. The headline is the generated
/// `fas_splash.g.dart` **config** (see [splashConfigDart]): a tiny data file
/// holding the resolved colours, timing, and the pre-rasterised logo/branding
/// bytes. The widget that consumes it ([AdaptiveSplash]) is baked into the same
/// generated file (see [splashRuntimeSource]), so the file depends only on
/// `package:flutter` and the user just wraps their app.
library;

import '../splash_runtime_source.dart';

/// The stock Flutter `launch_background.xml` (a plain `?android:colorBackground`
/// layer). `revert` restores this to `drawable/` and `drawable-v21/` instead of
/// deleting them: `LaunchTheme.windowBackground` still references
/// `@drawable/launch_background`, so removing the file outright would dangle that
/// reference and break the build.
const String stockLaunchBackgroundXml =
    '''<?xml version="1.0" encoding="utf-8"?>
<!-- Modify this file to customize your launch splash screen -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="?android:colorBackground" />

    <!-- You can insert your own image assets here -->
    <!-- <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/launch_image" />
    </item> -->
</layer-list>
''';

String _hex8(int argb) =>
    '0x${(argb & 0xFFFFFFFF).toRadixString(16).padLeft(8, '0').toUpperCase()}';

/// Builds `fas_splash.g.dart`: a single generated data file with the resolved
/// splash config, including base64-embedded PNG bytes for the logo/branding/
/// background image, so the in-app [AdaptiveSplash] needs no assets, no
/// `flutter_svg`, and no `device_info_plus`. The user wraps their app with the
/// package's `AdaptiveSplash`; this file is the only thing generated.
String splashConfigDart({
  required int bgLightArgb,
  required int bgDarkArgb,
  String? logoB64,
  String? logoDarkB64,
  String? brandingLightB64,
  String? brandingDarkB64,
  String? brandingText,
  int brandingTextColorLight = 0xFF000000,
  int brandingTextColorDark = 0xFFFFFFFF,
  String brandingAlignment = 'Alignment.bottomCenter',
  int brandingBottomDp = 48,
  String? bgImageLightB64,
  String? bgImageDarkB64,
  int logoSizeDp = 192,
  int? iosBgLightArgb,
  int? iosBgDarkArgb,
  String? iosLogoB64,
  String? iosLogoDarkB64,
  int? iosLogoSizeDp,
  int durationMs = 800,
  bool showOnAllVersions = false,
}) {
  // base64 uses only [A-Za-z0-9+/=], so it's safe inside a single-quoted literal.
  String bytes(String? b64) => b64 == null ? 'null' : "_b64('$b64')";
  String hexOrNull(int? argb) => argb == null ? 'null' : _hex8(argb);
  String intOrNull(int? v) => v == null ? 'null' : '$v';
  final text = brandingText == null
      ? 'null'
      : "'${brandingText.replaceAll(r'\', r'\\').replaceAll(r'$', r'\$').replaceAll("'", r"\'")}'";

  // Only pull in dart:convert/typed_data + the helper when there's artwork to
  // decode, so a colour-only splash leaves no unused imports in the user's app.
  final anyBytes = [
    logoB64,
    logoDarkB64,
    brandingLightB64,
    brandingDarkB64,
    bgImageLightB64,
    bgImageDarkB64,
    iosLogoB64,
    iosLogoDarkB64,
  ].any((b) => b != null);
  final convertImport = anyBytes ? "import 'dart:convert';\n" : '';
  final byteHelper =
      anyBytes ? '\n\nUint8List _b64(String s) => base64Decode(s);' : '';

  return '''
// GENERATED by flutter_adaptive_studio. Do not edit by hand.
// Re-run the generator to refresh it.
//
// Self-contained: depends only on package:flutter. Wrap your app to show the
// in-app splash. It matches the native one, holds briefly, then fades:
//
//     import 'fas_splash.g.dart';
//
//     void main() => runApp(
//           AdaptiveSplash(config: fasSplash, child: const MyApp()),
//         );
//
// Shows only where there's no native animated splash (Android API < 31) by
// default; force it everywhere with AdaptiveSplash(force: true, ...) or
// flutter_splash_all_versions: true under splash: in your config. Targets
// Android + iOS (uses dart:ffi, which is unavailable on web).
import 'dart:async';
${convertImport}import 'dart:ffi';
import 'dart:typed_data';

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;
import 'package:flutter/widgets.dart';

final FasSplashConfig fasSplash = FasSplashConfig(
  backgroundLight: ${_hex8(bgLightArgb)},
  backgroundDark: ${_hex8(bgDarkArgb)},
  logo: ${bytes(logoB64)},
  logoDark: ${bytes(logoDarkB64)},
  brandingLight: ${bytes(brandingLightB64)},
  brandingDark: ${bytes(brandingDarkB64)},
  brandingText: $text,
  brandingTextColorLight: ${_hex8(brandingTextColorLight)},
  brandingTextColorDark: ${_hex8(brandingTextColorDark)},
  brandingAlignment: $brandingAlignment,
  brandingBottomPadding: $brandingBottomDp,
  backgroundImageLight: ${bytes(bgImageLightB64)},
  backgroundImageDark: ${bytes(bgImageDarkB64)},
  logoSize: $logoSizeDp,
  // iOS overrides: used on iOS to match the iOS LaunchScreen (null = reuse the
  // values above). Branding is never drawn on iOS.
  iosBackgroundLight: ${hexOrNull(iosBgLightArgb)},
  iosBackgroundDark: ${hexOrNull(iosBgDarkArgb)},
  iosLogo: ${bytes(iosLogoB64)},
  iosLogoDark: ${bytes(iosLogoDarkB64)},
  iosLogoSize: ${intOrNull(iosLogoSizeDp)},
  duration: const Duration(milliseconds: $durationMs),
  showOnAllVersions: $showOnAllVersions,
);

$splashRuntimeSource$byteHelper
''';
}
