/// Drop-in Flutter glue emitted for the splash feature: a `FasSplash` widget
/// that mirrors the native splash (background + centre logo + bottom branding)
/// for devices WITHOUT the Android 12 `SplashScreen` API (SDK < 31), plus an
/// SDK gate and a guide. These are *references* the developer wires in.
library;

String _hex8(int argb) =>
    '0x${(argb & 0xFFFFFFFF).toRadixString(16).padLeft(8, '0').toUpperCase()}';

bool _isSvg(String? a) => a != null && a.toLowerCase().endsWith('.svg');

/// `Image.asset` can't render SVG — pick the right widget per asset type.
String _assetWidget(String asset, String sizeArgs) => _isSvg(asset)
    ? "SvgPicture.asset('$asset', $sizeArgs)"
    : "Image.asset('$asset', $sizeArgs)";

/// Statement that pre-decodes [asset] into its cache before the animation, so it
/// paints on the first frame instead of popping in mid-animation (which reads as
/// static). Block-scoped so multiple assets don't collide on the loader variable.
String _precacheStmt(String asset) => _isSvg(asset)
    ? '''{
        final loader = SvgAssetLoader('$asset');
        await svg.cache
            .putIfAbsent(loader.cacheKey(null), () => loader.loadBytes(null));
      }'''
    : "if (mounted) await precacheImage(const AssetImage('$asset'), context);";

/// Builds the `FasSplash` widget + SDK gate, with colours and asset paths baked
/// from the resolved splash config. Emits `SvgPicture.asset` for SVG sources
/// (and the `flutter_svg` import) and `Image.asset` for raster ones.
String splashFallbackDart({
  required int bgLightArgb,
  required int bgDarkArgb,
  String? logoAsset,
  String? brandingAsset,
  String? brandingDarkAsset,
  String brandingAlignment = 'Alignment.bottomCenter',
  int brandingBottomDp = 48,
  String? backgroundImageAsset,
  String? backgroundImageDarkAsset,
}) {
  // A distinct dark branding asset is themed by the active app brightness,
  // mirroring the native `-night` branding drawable.
  final hasDarkBrand =
      brandingDarkAsset != null && brandingDarkAsset != brandingAsset;
  final hasBgImage = backgroundImageAsset != null;
  final hasBgImageDark = backgroundImageDarkAsset != null &&
      backgroundImageDarkAsset != backgroundImageAsset;
  final needsSvg = _isSvg(logoAsset) ||
      _isSvg(brandingAsset) ||
      (hasDarkBrand && _isSvg(brandingDarkAsset)) ||
      _isSvg(backgroundImageAsset) ||
      (hasBgImageDark && _isSvg(backgroundImageDarkAsset));
  final svgImport =
      needsSvg ? "import 'package:flutter_svg/flutter_svg.dart';\n" : '';
  final svgPubReq = needsSvg
      ? '\n// Requires: flutter_svg  (flutter pub add flutter_svg)'
      : '';

  final logo = logoAsset == null
      ? '// No `image:` configured — add a static logo for the Flutter splash.\n'
          '              const SizedBox.shrink()'
      : _assetWidget(logoAsset, 'width: 192, height: 192');

  // Decode every asset into its cache BEFORE the animation starts.
  final precacheBody = [
    if (logoAsset != null) _precacheStmt(logoAsset),
    if (brandingAsset != null) _precacheStmt(brandingAsset),
    if (hasDarkBrand) _precacheStmt(brandingDarkAsset),
    if (hasBgImage) _precacheStmt(backgroundImageAsset),
    if (hasBgImageDark) _precacheStmt(backgroundImageDarkAsset),
  ].join('\n    ');

  // Full-bleed background image (theme-aware), drawn behind the logo.
  final bgImageWidget = !hasBgImage
      ? ''
      : hasBgImageDark
          ? 'dark ? ${_assetWidget(backgroundImageDarkAsset, 'fit: BoxFit.cover')} '
              ': ${_assetWidget(backgroundImageAsset, 'fit: BoxFit.cover')}'
          : _assetWidget(backgroundImageAsset, 'fit: BoxFit.cover');
  final bgImageBlock = !hasBgImage
      ? ''
      : '''
          // Full-bleed background image — mirrors the pre-31 windowBackground.
          Positioned.fill(child: $bgImageWidget),''';

  // Theme-aware branding widget: dark variant on a dark app theme when given.
  final brandingWidget = brandingAsset == null
      ? ''
      : hasDarkBrand
          ? 'dark ? ${_assetWidget(brandingDarkAsset, 'height: 40')} '
              ': ${_assetWidget(brandingAsset, 'height: 40')}'
          : _assetWidget(brandingAsset, 'height: 40');

  final brandingBlock = brandingAsset == null
      ? ''
      : '''
          // Bottom branding — mirrors windowSplashScreenBrandingImage.
          Align(
            alignment: $brandingAlignment,
            child: Padding(
              padding: const EdgeInsets.only(bottom: $brandingBottomDp),
              child: FadeTransition(
                opacity: _fade,
                child: $brandingWidget,
              ),
            ),
          ),''';

  return '''
// Generated by flutter_adaptive_studio. Safe to edit.
//
// A Flutter splash that mirrors the native one for devices without the
// Android 12 SplashScreen API (SDK < 31). Unlike the native splash, this one
// runs inside your app, so it follows your app theme. See SPLASH.md.
//
// Requires: device_info_plus  (flutter pub add device_info_plus)$svgPubReq
// Declare the logo/branding assets under `assets:` in pubspec.yaml.

import 'dart:io';

import 'package:device_info_plus/device_info_plus.dart';
import 'package:flutter/foundation.dart' show kDebugMode;
import 'package:flutter/material.dart';
$svgImport
/// True only on devices that have no native themed splash (Android < 12).
/// On 31+ the OS splash already themed correctly — don't show [FasSplash].
///
/// Pass [forceInDebug] (default true) to ALWAYS show it in debug builds so you
/// can see/iterate on [FasSplash] even on a modern device/emulator. Release
/// builds ignore the flag and use the real SDK check.
Future<bool> fasNeedsFlutterSplash({bool forceInDebug = true}) async {
  if (forceInDebug && kDebugMode) return true;
  if (!Platform.isAndroid) return false;
  final info = await DeviceInfoPlugin().androidInfo;
  return info.version.sdkInt < 31;
}

/// Solid background + centred logo (+ bottom branding) with a fade + gentle
/// pop-up entrance (quick ease-out fade, slight-overshoot scale). Colours come
/// from `background` / `background_dark` in your config.
class FasSplash extends StatefulWidget {
  const FasSplash({super.key});

  @override
  State<FasSplash> createState() => _FasSplashState();
}

class _FasSplashState extends State<FasSplash>
    with SingleTickerProviderStateMixin {
  static const Color _bgLight = Color(${_hex8(bgLightArgb)});
  static const Color _bgDark = Color(${_hex8(bgDarkArgb)});

  /// Like easeOutBack but with a stronger back (2.2 vs 1.56) for a clear spring.
  static const Curve _overshoot = Cubic(0.34, 2.2, 0.64, 1.0);

  late final AnimationController _c;
  late final Animation<double> _fade;
  late final Animation<double> _scale;

  @override
  void initState() {
    super.initState();
    // Rests at 0 → opacity 0 / scale 0.4, so the art is invisible until
    // forward(): it can mount and decode while hidden (see _decodeThenAnimate)
    // instead of popping in mid-animation.
    _c = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 1400));
    _fade = CurvedAnimation(
        parent: _c, curve: const Interval(0.0, 0.6, curve: Curves.easeOut));
    _scale = Tween<double>(begin: 0.4, end: 1.0)
        .animate(CurvedAnimation(parent: _c, curve: _overshoot));
    _decodeThenAnimate();
  }

  /// Decode the assets, then start the animation one frame later. The art loads
  /// asynchronously; animating during the decode (worsened by startup jank)
  /// makes it appear only once near full size — i.e. static.
  Future<void> _decodeThenAnimate() async {
    $precacheBody
    if (!mounted) return;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) _c.forward();
    });
  }

  @override
  void dispose() {
    _c.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      color: dark ? _bgDark : _bgLight,
      child: Stack(
        alignment: Alignment.center,
        children: [$bgImageBlock
          Center(
            child: FadeTransition(
              opacity: _fade,
              child: ScaleTransition(scale: _scale, child: $logo),
            ),
          ),$brandingBlock
        ],
      ),
    );
  }
}
''';
}

/// A zero-dependency drop-in that keeps the **native** splash on screen while
/// the app finishes starting up — the `FlutterNativeSplash.preserve/remove`
/// capability, but as generated code (pure Flutter framework, no plugin).
const String nativeSplashKeeperDart = r'''
// Generated by flutter_adaptive_studio. Safe to edit.
//
// Keeps the NATIVE splash on screen while your app finishes starting up —
// instead of a blank/white frame the instant Flutter's engine is ready but your
// first screen isn't. This is the windowBackground (Android < 12) / SplashScreen
// (Android 12+) / iOS launch screen the OS already shows; we just hold it.
//
// Pure Flutter framework: it defers the first frame until you call remove().
// No plugin, no native code, no method channel, no extra dependencies.
//
// Usage:
//   void main() {
//     final binding = WidgetsFlutterBinding.ensureInitialized();
//     FasNativeSplash.preserve(widgetsBinding: binding);
//     runApp(const MyApp());
//   }
//   // ...later, once your first screen is ready to be shown:
//   FasNativeSplash.remove();

import 'package:flutter/widgets.dart';

class FasNativeSplash {
  FasNativeSplash._();

  static WidgetsBinding? _binding;

  /// Call right after `WidgetsFlutterBinding.ensureInitialized()` in `main()`,
  /// BEFORE `runApp()`. Holds back Flutter's first frame so the native splash
  /// stays visible during your startup work (async init, first build, etc.).
  static void preserve({required WidgetsBinding widgetsBinding}) {
    _binding = widgetsBinding..deferFirstFrame();
  }

  /// Lets Flutter paint its first frame, replacing the native splash with your
  /// UI. Call once your app is ready. Safe to call more than once.
  static void remove() {
    _binding?.allowFirstFrame();
    _binding = null;
  }
}
''';

const String splashGuide = r'''
# Splash screen — native + Flutter fallback

## Requirement: compileSdk ≥ 31
The Android 12 `SplashScreen` attributes (`windowSplashScreenBackground`,
`windowSplashScreenAnimatedIcon`, `windowSplashScreenBrandingImage`, …) live in
SDK 31+. The generated `values-v31/` styles compile against them, so your
`android/app/build.gradle(.kts)` must use **compileSdk 31 or higher** (34
recommended). If you see `error: style attribute 'android:attr/windowSplashScreen…'
not found`, that's the fix.

## Icon keyline (why your logo isn't clipped)
Android 12 masks the splash icon to a **centred circle of 2/3 the canvas**:
288dp canvas → ⌀192dp safe circle (no icon background), or 240 → ⌀160 (with one).
Anything outside that circle is **cut**. The generator inscribes your logo's
bounding box inside the safe circle (diagonal ≤ diameter), so even a square logo's
corners stay visible. If your icon still looks small, it's because the circle is
only 2/3 of the canvas — that's the spec, not a bug.

flutter_adaptive_studio generated the **native** Android splash:

- **Android 12+ (API 31+):** the real `SplashScreen` API — `values-v31/styles.xml`
  (+ `-night`) with `windowSplashScreenBackground`, `windowSplashScreenAnimatedIcon`
  (your `image:`/`animated_icon:`), an optional `windowSplashScreenIconBackgroundColor`,
  and `windowSplashScreenBrandingImage` (your `branding:`). Themed by the **system**.

  The animated icon must be a ready-made **AnimatedVectorDrawable** (`.xml`),
  used verbatim — author it in any AVD tool (e.g. Shapeshifter → "Export →
  Animated Vector Drawable"). Lottie is **not** supported by the native splash
  (runtime-only) — use it in the Flutter fallback below instead. Animated icons
  are masked to the same keyline circle, so design the animation inside it (we
  don't reshape it).
- **Android < 12:** a classic `windowBackground` (`drawable/launch_background.xml`)
  with the logo centred and branding at the bottom. Light/dark via `-night`.

## Keep the native splash during startup (no white flash) — `fas_native_splash.dart`
The OS shows the native splash only until Flutter paints its **first frame**.
If your app still has work to do then (load prefs, open a DB, check auth), that
first frame is blank/white and pops in late. `FasNativeSplash` holds the native
splash until *you* say the app is ready — by deferring the first frame. It's
pure Flutter framework: **no plugin, no native code, no extra dependencies.**

```dart
import 'flutter_adaptive_studio/splash/fas_native_splash.dart';

void main() {
  final binding = WidgetsFlutterBinding.ensureInitialized();
  FasNativeSplash.preserve(widgetsBinding: binding); // hold the native splash
  runApp(const MyApp());
}

// ...after your async init / once your first screen is ready:
FasNativeSplash.remove(); // let Flutter paint; native splash hands off to your UI
```

This works on **every** API level (it's just the native splash, kept longer) and
is independent of the Flutter fallback below. Migrating from flutter_native_splash?
The `preserve`/`remove` signatures match, so it's a drop-in swap.

### Where to call `remove()`
Call it right after the **first frame of the first screen you want the user to
see** has painted — i.e. from a post-frame callback. Too early brings the white
flash back; never calling it strands the app on the splash. Two questions decide:
(1) is there async startup work (prefs/DB/auth) before the first usable screen,
and (2) during it, should the user see the frozen native splash or your own
Flutter screen?

- **No async work** → remove in your first screen's `initState`:
  ```dart
  WidgetsBinding.instance.addPostFrameCallback((_) => FasNativeSplash.remove());
  ```
- **Async work, native splash covers it** → easiest is to `await` it BEFORE
  `runApp()` (the splash is then held for free); or `preserve()` + `remove()`
  after the real screen's first frame. Keep it short — a frozen splash > ~2s
  reads as a hang.
  ```dart
  Future<void> main() async {
    final binding = WidgetsFlutterBinding.ensureInitialized();
    FasNativeSplash.preserve(widgetsBinding: binding);
    try {
      await loadEverything();
    } finally {
      runApp(const MyApp());
      FasNativeSplash.remove();
    }
  }
  ```
- **Async work, your own loader** → call `remove()` right after your LOADER
  screen's first frame, then do the work behind your Flutter UI.

Guardrails: guarantee `remove()` runs on every path (wrap init in `try/finally`),
call it once, and keep the held time short — the native splash can't animate or
show progress, so hand off to Flutter quickly for long loads.

## Why the Flutter fallback?
The native splash renders **before** your app code runs, so it can only follow
the **system** theme — and on **Android ≤ 9** there's no system dark mode at all,
so it always shows light. If you want the splash to follow your **app** theme on
those devices, show `FasSplash` as your first screen, gated by SDK version.

```dart
// 1) flutter pub add device_info_plus   (+ flutter_svg if your logo is SVG)
// 2) Declare your logo/branding under `assets:` in pubspec.yaml.
// 3) At app start:
final showFlutter = await fasNeedsFlutterSplash(); // true on Android < 12
// Debug builds force it ON by default so you can see it on any device/emulator.
// To test the real gate in debug: fasNeedsFlutterSplash(forceInDebug: false).
runApp(MyApp(showSplash: showFlutter));

// In your first route, if showSplash: show FasSplash for ~600ms (or until
// your app is ready), then navigate to home. On 31+ skip it entirely — the
// native splash already covered the launch.
```

## Avoiding a flicker at handoff
For a seamless transition, `FasSplash`'s background + logo geometry already match
the native splash. Keep the native splash short and render `FasSplash` on the
first frame so there's no visible gap (most noticeable on Android ≤ 9 going dark).

## Other splash options (set in your config)
- **Dark variants:** `background_dark`, `image_dark`, `icon_background_dark`,
  `branding_dark`, `animated_icon_dark` — emitted to `-night` and chosen by the
  system (native) / app theme (fallback).
- **`background_image`** (+ `_dark`) — full-bleed background behind the logo on
  the pre-31 splash + Flutter fallback. The Android 12+ system splash takes a
  colour only, so it uses `background` there.
- **`branding_mode`** (`bottom` / `bottom_left` / `bottom_right`) +
  **`branding_bottom_padding`** — branding placement (pre-31 + fallback; the
  system splash always bottom-centres).
- **`gravity`** — pre-31 centre-image alignment. **`fullscreen`** — hide the
  system bars. **`screen_orientation`** — lock orientation (app-wide; written to
  the shared manifest, so `revert` won't undo it).

## Flavors
One config, base + per-flavor overrides under `flavors:`. Generate a flavor with
`--flavor <name>` and the merged result is written to that flavor's
`android/app/src/<name>/res` overlay (it overrides `main` for that build):

```yaml
flutter_adaptive_studio:
  android: { ... }            # base config
  flavors:
    dev:  { android: { splash: { background: "#00C853" } } }
```
''';
