/// Drop-in runtime glue + guide emitted for the Phase 4 themed-icon feature.
/// These are *references* the developer wires in: the alias toggle is inherently
/// app-side, so we hand over correct, copy-pasteable code plus the caveats.
library;

const String themedIconKotlin = r'''
// Generated by flutter_adaptive_studio.
// TODO: change the package below to your applicationId, then move this file
// into android/app/src/main/kotlin/<your/package/path>/.

package com.example.app

import android.content.ComponentName
import android.content.Context
import android.content.pm.PackageManager

/**
 * Switches the launcher icon by enabling one activity-alias and disabling the
 * others. Call this from the background (e.g. Activity.onStop) to avoid the
 * launcher relaunching your task.
 */
object FasIconSwitcher {
    private val variants = listOf("Light", "Dark")

    fun setIcon(context: Context, variant: String) {
        val pm = context.packageManager
        val pkg = context.packageName
        for (v in variants) {
            val enabled = v.equals(variant, ignoreCase = true)
            pm.setComponentEnabledSetting(
                ComponentName(pkg, "$pkg.FasIcon$v"),
                if (enabled) PackageManager.COMPONENT_ENABLED_STATE_ENABLED
                else PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                PackageManager.DONT_KILL_APP
            )
        }
    }
}
''';

const String themedIconDart = r'''
// Generated by flutter_adaptive_studio.
import 'package:flutter/services.dart';

/// Requests a launcher-icon variant switch ("Light" or "Dark").
/// Best called when the app is backgrounded to avoid a relaunch flash.
class AdaptiveIconSwitcher {
  static const _channel = MethodChannel('flutter_adaptive_studio/icon');

  static Future<void> setVariant(String variant) =>
      _channel.invokeMethod<void>('setIcon', {'variant': variant});

  static Future<void> light() => setVariant('Light');
  static Future<void> dark() => setVariant('Dark');
}
''';

const String themedIconGuide = r'''
# Themed (light/dark) launcher icons

flutter_adaptive_studio generated two full-colour adaptive icons and wired
`activity-alias` entries (`FasIconLight`, `FasIconDark`) in your
AndroidManifest.xml. Exactly one alias is enabled at a time; switching is done
at runtime by your app.

> ⚠️ Android has **no** automatic "swap launcher icon by system theme". This is
> the only mechanism for two *different full-colour* icons, and it has costs:
> - Toggling an alias can **relaunch** your task. Switch in the background
>   (`onStop`) to hide it (the Blinkit/Meesho approach).
> - Shipped aliases are **permanent**. Never delete one a user might have
>   enabled, or their icon vanishes.
> - **OEM launchers vary** (Samsung/Xiaomi/OnePlus vs Pixel) and may cache the
>   old icon briefly.
> For a side-effect-free theme-reactive icon, prefer the **monochrome** themed
> icon (Android 13+), already generated if you supplied `monochrome:`.

## Wiring (3 steps)

1. Move `FasIconSwitcher.kt` into `android/app/src/main/kotlin/<your/package>/`
   and set its `package` to your applicationId.

2. Register the channel in `MainActivity.kt`:

   ```kotlin
   import io.flutter.embedding.android.FlutterActivity
   import io.flutter.embedding.engine.FlutterEngine
   import io.flutter.plugin.common.MethodChannel

   class MainActivity : FlutterActivity() {
       override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
           super.configureFlutterEngine(flutterEngine)
           MethodChannel(flutterEngine.dartExecutor.binaryMessenger,
               "flutter_adaptive_studio/icon").setMethodCallHandler { call, result ->
               if (call.method == "setIcon") {
                   FasIconSwitcher.setIcon(this, call.argument<String>("variant") ?: "Light")
                   result.success(null)
               } else result.notImplemented()
           }
       }
   }
   ```

3. Copy `icon_switcher.dart` into your `lib/` and call it, ideally when the app
   is backgrounded, after detecting the platform brightness:

   ```dart
   final dark = MediaQuery.platformBrightnessOf(context) == Brightness.dark;
   await AdaptiveIconSwitcher.setVariant(dark ? 'Dark' : 'Light');
   ```
''';
