// Generated by flutter_adaptive_studio. Safe to edit.
//
// A Flutter splash that mirrors the native one for devices without the
// Android 12 SplashScreen API (SDK < 31). Unlike the native splash, this one
// runs inside your app, so it follows your app theme. See SPLASH.md.
//
// Requires: device_info_plus  (flutter pub add device_info_plus)
// Requires: flutter_svg  (flutter pub add flutter_svg)
// Declare the logo/branding assets under `assets:` in pubspec.yaml.

import 'dart:io';

import 'package:device_info_plus/device_info_plus.dart';
import 'package:flutter/foundation.dart' show kDebugMode;
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

/// True only on devices that have no native themed splash (Android < 12).
/// On 31+ the OS splash already themed correctly — don't show [FasSplash].
///
/// Pass [forceInDebug] (default true) to ALWAYS show it in debug builds so you
/// can see/iterate on [FasSplash] even on a modern device/emulator. Release
/// builds ignore the flag and use the real SDK check.
Future<bool> fasNeedsFlutterSplash({bool forceInDebug = true}) async {
  if (forceInDebug && kDebugMode) return true;
  if (!Platform.isAndroid) return false;
  final info = await DeviceInfoPlugin().androidInfo;
  return info.version.sdkInt < 31;
}

/// Solid background + centred logo (+ bottom branding) with a fade + gentle
/// pop-up entrance (quick ease-out fade, slight-overshoot scale). Colours come
/// from `background` / `background_dark` in your config.
class FasSplash extends StatefulWidget {
  const FasSplash({super.key});

  @override
  State<FasSplash> createState() => _FasSplashState();
}

class _FasSplashState extends State<FasSplash>
    with SingleTickerProviderStateMixin {
  static const Color _bgLight = Color(0xFFFBFAF5);
  static const Color _bgDark = Color(0xFF0E1A1C);

  /// Like easeOutBack but with a stronger back (2.2 vs 1.56) for a clear spring.
  static const Curve _overshoot = Cubic(0.34, 2.2, 0.64, 1.0);

  late final AnimationController _c;
  late final Animation<double> _fade;
  late final Animation<double> _scale;

  @override
  void initState() {
    super.initState();
    // Rests at 0 → opacity 0 / scale 0.4, so the art is invisible until
    // forward(): it can mount and decode while hidden (see _decodeThenAnimate)
    // instead of popping in mid-animation.
    _c = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 1400));
    _fade = CurvedAnimation(
        parent: _c, curve: const Interval(0.0, 0.6, curve: Curves.easeOut));
    _scale = Tween<double>(begin: 0.4, end: 1.0)
        .animate(CurvedAnimation(parent: _c, curve: _overshoot));
    _decodeThenAnimate();
  }

  /// Decode the assets, then start the animation one frame later. The art loads
  /// asynchronously; animating during the decode (worsened by startup jank)
  /// makes it appear only once near full size — i.e. static.
  Future<void> _decodeThenAnimate() async {
    {
        final loader = SvgAssetLoader('assets/listkin_logo.svg');
        await svg.cache
            .putIfAbsent(loader.cacheKey(null), () => loader.loadBytes(null));
      }
    {
        final loader = SvgAssetLoader('assets/wordmark.svg');
        await svg.cache
            .putIfAbsent(loader.cacheKey(null), () => loader.loadBytes(null));
      }
    {
        final loader = SvgAssetLoader('assets/wordmark_dark.svg');
        await svg.cache
            .putIfAbsent(loader.cacheKey(null), () => loader.loadBytes(null));
      }
    if (!mounted) return;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) _c.forward();
    });
  }

  @override
  void dispose() {
    _c.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      color: dark ? _bgDark : _bgLight,
      child: Stack(
        alignment: Alignment.center,
        children: [
          Center(
            child: FadeTransition(
              opacity: _fade,
              child: ScaleTransition(scale: _scale, child: SvgPicture.asset('assets/listkin_logo.svg', width: 192, height: 192)),
            ),
          ),          // Bottom branding — mirrors windowSplashScreenBrandingImage.
          Align(
            alignment: Alignment.bottomCenter,
            child: Padding(
              padding: const EdgeInsets.only(bottom: 48),
              child: FadeTransition(
                opacity: _fade,
                child: dark ? SvgPicture.asset('assets/wordmark_dark.svg', height: 40) : SvgPicture.asset('assets/wordmark.svg', height: 40),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
