// Generated by flutter_adaptive_studio.
// TODO: change the package below to your applicationId, then move this file
// into android/app/src/main/kotlin/<your/package/path>/.

package com.example.app

import android.content.ComponentName
import android.content.Context
import android.content.pm.PackageManager

/**
 * Switches the launcher icon by enabling one activity-alias and disabling the
 * others. Call this from the background (e.g. Activity.onStop) to avoid the
 * launcher relaunching your task.
 */
object FasIconSwitcher {
    private val variants = listOf("Light", "Dark")

    fun setIcon(context: Context, variant: String) {
        val pm = context.packageManager
        val pkg = context.packageName
        for (v in variants) {
            val enabled = v.equals(variant, ignoreCase = true)
            pm.setComponentEnabledSetting(
                ComponentName(pkg, "$pkg.FasIcon$v"),
                if (enabled) PackageManager.COMPONENT_ENABLED_STATE_ENABLED
                else PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                PackageManager.DONT_KILL_APP
            )
        }
    }
}
