// Generated by flutter_adaptive_studio.
import 'package:flutter/services.dart';

/// Requests a launcher-icon variant switch ("Light" or "Dark").
/// Best called when the app is backgrounded to avoid a relaunch flash.
class AdaptiveIconSwitcher {
  static const _channel = MethodChannel('flutter_adaptive_studio/icon');

  static Future<void> setVariant(String variant) =>
      _channel.invokeMethod<void>('setIcon', {'variant': variant});

  static Future<void> light() => setVariant('Light');
  static Future<void> dark() => setVariant('Dark');
}
